### ISSUE TITLE
For deployment in ICP the persistent volume claims must be named xxxx-ibm-microclimate

### ISSUE THREAD

**Issue by jxadro** [microclimate-dev2ops/microclimate-dev2ops.github.io#11]
Hi.

I have installed Microclimate 1.0.0 on ICP 2.1.0.2

I created two PV and two PVC, the name of the PVC were microclimateworkspace and microclimate jenkins.
I tested setting dynamic provisioning to true and to false.

After successful installation I created a new java-liberty project and it never started.
In the logs of the container microclimate-file-watcher I could see this error:
Error: release mc-testjava-c3fa7e510f345d29bfd90d24893fcb9dcc812191 failed: Deployment.apps "mc-testjava-c3fa7e510f345d29bfd90d24893fcb9dcc812191-idc" is invalid: [spec.template.spec.volumes[0].persistentVolumeClaim.claimName: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "shared-workspace"]

Looking at the generated files in the workspace I found this:

"microclimate workspace"/.idc/docker/docker-<your docker>/artifacts# cat run_kubernetes.sh
There is this line: PVC_NAME="$( kubectl get pvc | grep '\-ibm-microclimate' | cut -d ' ' -f 1 )";

So it seems that in case of using your own persistent volume claims, the name for the workspace one must be "something"-ibm-microclimate.

I unistalled, installed it again setting that kind of name (workspace-ibm-microclimate) and it worked.

I have not found this "restriction" in the documentation.

**Comment by jagraj** [comment]
Thanks Javier

@micgibso 
I am copying Michael to go through this and update our docs.

**Comment by micgibso** [comment]
Limitation now documented, see https://microclimate-dev2ops.github.io/installicp
Provide persistent storage volumes -> new paragraph 2
