### ISSUE TITLE
Persistent Volume Claims must be created for Jenkins when using a non-default dynamic storage provisioner

### ISSUE THREAD

**Issue by timroster** [microclimate-dev2ops/microclimate-dev2ops.github.io#13]
When deploying with a non-default storage class for dynamic provisioning, the microclimate 1.0.0 chart does not capture a value to use for the storage class name with the Jenkins chart template. 

As a result, it's possible to use a non-default dynamic storage class for the microclimate workspace persistent storage only.

Chart documentation should be updated to indicate that for Jenkins, you need to create a persistent volume claim and provide it to the chart when using a non-default storage class for dynamic provisioning.

**Comment by clarkja** [comment]
@timroster please can you provide a link to the pages that need to be updated.

**Comment by clarkja** [comment]
The ID team do not control this page https://github.com/IBM/charts/blob/master/stable/ibm-microclimate/README.md (which is practically the same as the installicp page which we do control). So we are in discussion with Robert Taniwa to alter the first to point to the second to avoid out of date info etc. 
Issue on hold atm....

**Comment by clarkja** [comment]
Results of discussion within the team on how to fix this is that we now, on Microclimate pages, link to the readme on ICP. see https://github.ibm.com/dev-ex/landing-pages/pull/114
