### ISSUE TITLE
Community page should have link for creating new issues

### ISSUE THREAD

**Issue by docwhat** [microclimate-dev2ops/microclimate-dev2ops.github.io#17]
Currently, it is not obvious where to file issues for microclimate itself.

Going to the [community page](https://microclimate-dev2ops.github.io/community) shows two links to the `microclimate-dev2ops` GitHub organization, but no links to any place where an actual issue could be filed.

> #### Find something that needs to be improved?
>Found a bug? Have a recommendation on something we can do to improve the Microclimate experience? We opened up shop on [GitHub](https://github.com/orgs/microclimate-dev2ops)! And while our moving vans haven’t all arrived yet, they are all in transit. In the meantime, we have enough of [our project](https://github.com/orgs/microclimate-dev2ops) in place to start working with you. Help us help you!

There is microclimate-dev2ops/microclimate-release#1 but it is ancient and nobody has ever replied to it.

What I expected was a clear link to a place to file issues.

**Comment by micgibso** [comment]
Thanks for raising this @docwhat . Will enhance the community page and add a link directly to the Issues page that you have raised these on, ie. https://github.com/microclimate-dev2ops/microclimate-dev2ops.github.io/issues.

**Comment by micgibso** [comment]
Community page enhanced, see: https://microclimate-dev2ops.github.io/community
