### ISSUE TITLE
IBM Cloud private should be IBM Cloud Private?

### ISSUE THREAD

**Issue by yeekangc** [microclimate-dev2ops/microclimate-dev2ops.github.io#2]
The "IBM Cloud private" in "Microclimate can be installed locally or on IBM Cloud private" on https://microclimate-dev2ops.github.io/ should be "IBM Cloud Private"?

**Comment by micgibso** [comment]
@yeekangc Went to resolve this today but found that I'd have to fork the docs repo, change the file (index.html) and then create the pull request; this isn't what we (Jacqs Clarke and I) usually do, so queried it on Slack and David Currie is adding us as contributors.  Am on vacation tomorrow, will take another look on Wednesday.

**Comment by micgibso** [comment]
Reviewed, approved, closing...
