### ISSUE TITLE
Running ./cli/install.sh causes unexpected problems

### ISSUE THREAD

**Issue by docwhat** [microclimate-dev2ops/microclimate-dev2ops.github.io#20]
If you run `./cli/install.sh` instead of `cd cli && ./install.sh` you get errors, such as not being able to find `../.env`.

There are two problems here:

1. The bash script didn't exit immediately.

    I usually set my bash scripts to do `set -eEu` at the top.  Sometimes I add `set -o pipefail` as well.

    This leaves a [large smoking crater](https://docwhat.org/smoking-craters-are-good) if something goes wrong, which is a good thing.

    If you need better debugging, you can use [bash tracebacks](https://docwhat.org/tracebacks-in-bash) to get better info out.
2. The script should work regardless of where it is run from.  It may need to [change directory to where the script is](https://stackoverflow.com/questions/3349105/how-to-set-current-working-directory-to-the-directory-of-the-script).

**Comment by sishida** [comment]
Thank you for opening this issue and letting us know about the problems! I have notified the appropriate team to work on updates. Thank you!

**Comment by rnchamberlain** [comment]
This is fixed in the latest release of Microclimate, 19.05, available Friday 31 May 2019, see https://microclimate.dev/news

The fix allows you to run the install script from any location.
