### ISSUE TITLE
Pipeline - Connect to remote (Github) workplace error

### ISSUE THREAD

**Issue by bunjolah** [microclimate-dev2ops/microclimate-dev2ops.github.io#21]
Error Message: Could not connect Check URL and credentials.

I get this message for both my Github password and personal access token. Before using the Pipeline GUI, I added the remote repository via the Theia terminal. "git remote -v" verifies that the remote repository was successfully added. Why is the GUI saying that I am not connected to any remote workplace?

**Comment by mnuttall** [comment]
Hi Jennifer the pipeline section of the GUI needs for there to be a Microclimate instance running on IBM Cloud Private. If you are using Microclimate on your local workstation then the GUI wants you to connect it to that remote instance - so the credentials its asking for are those required to log you into the IBM Cloud Private cluster that your remote Microclimate instance is running on.
