### ISSUE TITLE
Updates to microclimate landing page for 2018_M3 Driver

### ISSUE THREAD

**Issue by mmulholl** [microclimate-dev2ops/microclimate-dev2ops.github.io#5]
We are updating the beta driver for the M3 Driver.  Things to be done:
- Update link to new driver.
- Provide instructions on how to update the driver (add uninstall instructions?)
- Add a notice somewhere that the driver has been updated.
- Add information on what is new in the driver

**Comment by tobespc** [comment]
To update the links to the new driver, we need to give a new zip of https://github.ibm.com/dev-ex/microclimate-release/tree/2018_M3

**Comment by tobespc** [comment]
To update the driver, users will be required to re install from this new zip

**Comment by mmulholl** [comment]
I am working on updates to add uninstall instructions
 but cannot assign this issue to myself :-(

**Comment by micgibso** [comment]
Checked with Martin, work complete, closing...
