### ISSUE TITLE
Would like to be able to delete templates

### ISSUE THREAD

**Issue by JoshuaOliphant** [microclimate-dev2ops/microclimate-dev2ops.github.io#50]
* Installation type:
   * Local (mac)
* Problem description:
   * There is option to create new templates, but would like to be able to delete template as well.

**Comment by tetchel** [comment]
Hey Joshua, thanks for the issue report!

This feature is on our roadmap. In the meantime, you can delete templates from `microclimate-workspace/.extensions/$templateName`.

**Comment by tetchel** [comment]
This feature is available in the newest release 19.02
