### ISSUE TITLE
Tutorials are out of date

### ISSUE THREAD

**Issue by trbryant2** [microclimate-dev2ops/microclimate-dev2ops.github.io#58]
I'm just getting up to speed on Microclimate and have found several instances in the tutorials where things are out of date.
1)  The page that describes how to utilize [kibana](https://microclimate-dev2ops.github.io/installkibanafilter#doc ) references deprecated Helm charts.
2) The video that demonstrates how to [Work with Projects](https://microclimate-dev2ops.github.io/usingmicroclimate#doc) doesn't demonstrate how to access the project that was created.  The URL in the video was not valid.

**Comment by sishida** [comment]
Thank you for opening this issue and letting us know about our out-of-date tutorials. I have notified the appropriate team to work on updates. Thank you!

**Comment by sishida** [comment]
We have updated the page and the video. The updated page is scheduled to appear with the next Microclimate release, and the updated video is already ready for viewing. :)

**Comment by sishida** [comment]
- We have updated the "Installing Kibana and filtering logs in IBM Cloud Private" page: https://microclimate.dev/installkibanafilter
- We have updated the "Working with projects" video: https://microclimate.dev/usingmicroclimate#doc
