### ISSUE TITLE
microclimate header is too big

### ISSUE THREAD

**Issue by deboer-tim** [microclimate-dev2ops/microclimate-dev2ops.github.io#7]
I went to the microclimate homepage today on a hotel network and it loaded slowly (as every site did) and eventually completed ok except that the header image was missing. I tried reloading a couple times and couldn't make it appear.

When I dug into it and tried to load the header directly (microclimate_header.png) it took about 2 minutes to load the entire image. Then I checked, and it was 4Mb (!) - no wonder it didn't load when even 100K files were slow.

We need to reduce the initial download size of the header to < 1Mb.

**Comment by travis1111** [comment]
Thanks for spotting this issue.  We were using PNGs, I converted them to jpg, the 4MB file is not 256KB should load faster now.  Thanks!

The fix was pushed to the repo one minute ago.

**Comment by deboer-tim** [comment]
Awesome, loads much faster now!
